### ISSUE TITLE
YouTube percentages not used

### ISSUE THREAD

**Issue by dbarlett** [CardinalPath/gas#24] opened 2012-05-11 03:22 UTC
I followed the example in the readme to add `percentages: [25, 50, 75, 90]` to the `_gasTrackYoutube` call, but did not see any percentage events in GA. Stepping thru in Firebug showed that lines 209-215 of youtube.js result in `opts = {}` and thus `opts['percentages'] = []`.

**Comment by eduardocereto** [comment] 2012-05-11 03:45
I can't reproduce this. It works for me. I'll close this because it doesn't have enough information. `opts` is not overwritten if you send a parameter to `_gasTrackYoutube`. You can either reopen it with an example of a page that is broken or a pull request of the supposed fix.

You should not see youtube.js on Firebug. You should use one of the compiled files from the Download page:

https://github.com/CardinalPath/gas/downloads

**Comment by dbarlett** [comment] 2012-05-11 04:24
Can you provide a working example page so I can determine if my browsers are at fault?

Example page: http://dylanbarlett.com/gastest.html

Steps to reproduce:
1. Copy unminified gas.js to server.
2. Supply percentages in call to `_gasTrackYoutube` per readme.
3. Start and pause video.
4. Observe that GET requests are made to __utm.gif with play and pause events, as expected. Confirm that events are shown in Google Analytics.
5. Observe no GET requests are made with percentage events, and no events are shown in GA.

Debugging:
1. Set breakpoint on line 1534 of gas.js
2. Watch value of `opts = Object { force=false, category="YouTube Video", percentages=[0]}`

**Comment by eduardocereto** [comment] 2012-05-11 04:53
You're right. Thanks for pointing it out. I think I need some sleep.

**Closed as completed** 2012-05-11 05:08 UTC
Labels: bug

**Comment by eduardocereto** [comment] 2012-05-11 05:12
I just uploaded v1.8 with this fix. Let m know if that works for you.

https://github.com/CardinalPath/gas/downloads

**Comment by dbarlett** [comment] 2012-05-11 16:15
Thanks for the fix. gas.js downloads fine, but gas.min.js results in File was not found.

**Comment by eduardocereto** [comment] 2012-05-14 08:29
@dbarlett fixed

**Comment by dijust** [comment] 2013-03-19 03:03
Hi,

This is still a problem for me. Was this fix ever confirmed?

Thx
Justin

**Comment by dbarlett** [comment] 2013-03-19 13:00
Works for me, calling v1.10.1 from cdnjs.
